package com.wy.domain;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.wy.extend.ParamName;
import org.hibernate.validator.constraints.Length;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;

@JsonInclude(value = JsonInclude.Include.NON_NULL)
public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.name
     *
     * @mbg.generated
     */
    @Length(min = 6, max = 10)
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.actual_age
     *
     * @mbg.generated
     */
    @JsonProperty("actual_age")
    @ParamName("actual_age")
    @Min(value = 18, message = "{Max.user.actualAge}")
    @Max(100)
    private Integer actualAge;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.actual_age
     *
     * @return the value of user.actual_age
     *
     * @mbg.generated
     */
    public Integer getActualAge() {
        return actualAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.actual_age
     *
     * @param actualAge the value for user.actual_age
     *
     * @mbg.generated
     */
    public void setActualAge(Integer actualAge) {
        this.actualAge = actualAge;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", actualAge=" + actualAge +
                '}';
    }
}